// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSViCvGgJURa1FC5vO07TgaBgHwg87YYE',
    appId: '1:999542532498:web:04e72dddd4b2f5edeb794b',
    messagingSenderId: '999542532498',
    projectId: 'inmailfix',
    authDomain: 'inmailfix.firebaseapp.com',
    storageBucket: 'inmailfix.firebasestorage.app',
    measurementId: 'G-N6QS98GKP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBki9YqvVOx1G9kspf40O5RC1qWa517gj8',
    appId: '1:999542532498:android:fd5698c386967f8eeb794b',
    messagingSenderId: '999542532498',
    projectId: 'inmailfix',
    storageBucket: 'inmailfix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5-KrjdjlJzR1qJ38Tpm607DSO-Hw-oy8',
    appId: '1:999542532498:ios:23d183dc04b913abeb794b',
    messagingSenderId: '999542532498',
    projectId: 'inmailfix',
    storageBucket: 'inmailfix.firebasestorage.app',
    iosBundleId: 'com.example.fixmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5-KrjdjlJzR1qJ38Tpm607DSO-Hw-oy8',
    appId: '1:999542532498:ios:23d183dc04b913abeb794b',
    messagingSenderId: '999542532498',
    projectId: 'inmailfix',
    storageBucket: 'inmailfix.firebasestorage.app',
    iosBundleId: 'com.example.fixmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSViCvGgJURa1FC5vO07TgaBgHwg87YYE',
    appId: '1:999542532498:web:218cbccc53d63d44eb794b',
    messagingSenderId: '999542532498',
    projectId: 'inmailfix',
    authDomain: 'inmailfix.firebaseapp.com',
    storageBucket: 'inmailfix.firebasestorage.app',
    measurementId: 'G-0GR35WZCXJ',
  );
}
